cask 'iterm2'

brew 'zsh'
brew 'coreutils'
brew 'curl'
brew 'unrar'
cask 'the-unarchiver'
brew 'wget'

brew 'tmux'

brew 'vim', args: [ 'without-perl', 'without-ruby', 'without-python' ]
brew 'ctags'
brew 'ripgrep'
brew 'fzf'

brew 'git'
brew 'mercurial'

brew 'cmake'
brew 'shellcheck'
brew 'valgrind'
brew 'llvm', args: [ 'with-clang-extra-tools', 'with-clang' ]

brew 'ansible'
brew 'packer'
cask 'vagrant'
cask 'virtualbox'

cask 'flux'
cask 'yujitach-menumeters'

brew 'python3'
